type: intersection
files:
  - "/content/drive/My Drive/ToxicSpans/results/combine_predictions/spans-pred-original_test-union_roberta_token_best_3_ckpts.txt"
  - "/content/drive/My Drive/ToxicSpans/results/spanbert_spans/preds/spans-pred-original_test.txt"
path: "/content/drive/My Drive/ToxicSpans/results/combine_predictions/spans-pred-original_test-intersection_spanbert_spans_union_roberta_token_best_3_ckpts.txt"
