type: union
files:
  - "/content/drive/MyDrive/ToxicSpans/results/spanbert_spans/spanbert_spans_best_3_ckpts/preds-3000/spans-pred-original_test.txt"
  - "/content/drive/MyDrive/ToxicSpans/results/spanbert_spans/spanbert_spans_best_3_ckpts/preds-3500/spans-pred-original_test.txt"
  - "/content/drive/MyDrive/ToxicSpans/results/spanbert_spans/spanbert_spans_best_3_ckpts/preds-4000/spans-pred-original_test.txt"
path: "/content/drive/MyDrive/ToxicSpans/results/combine_predictions/spans-pred_original_test-union_spanbert_spans_best_3_ckpts.txt"
